name: crud_firebase
description: Ignite CRUD - Firebase.
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  firebase_core_web: ^2.17.4
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.1
  google_fonts: ^6.2.1
  json_serializable: ^6.8.0
  mobx: ^2.3.3
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
